version: '3'
services:

  shell:
    # Makefile fills PROJECT_NAME to current directory name.
    # add UID to allow multiple users run this in parallel
    container_name: ${PROJECT_NAME}_${HOST_UID:-4000}
    hostname: ${PROJECT_NAME}
    # These variables are passed into the container.
    environment:
      - PWD=${PWD}
      - UMBREL=${UMBREL}
      - THIS_FILE=${THIS_FILE}
      - TIME=${TIME}
      - HOST_USER=${HOST_USER}
      - HOST_UID=${HOST_UID}
      - SERVICE_TARGET=${SERVICE_TARGET}
      - ALPINE_VERSION=${ALPINE_VERSION}
      - WHISPER_VERSION=${WHISPER_VERSION}
      - CARBON_VERSION=${CARBON_VERSION}
      - GRAPHITE_VERSION=${GRAPHITE_VERSION}
      - STATSD_VERSION=${STATSD_VERSION}
      - GRAFANA_VERSION=${GRAFANA_VERSION}
      - PROJECT_NAME=${PROJECT_NAME}
      - GIT_USER_NAME=${GIT_USER_NAME}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL}
      - GIT_SERVER=${GIT_SERVER}
      - GIT_PROFILE=${GIT_PROFILE}
      - GIT_BRANCH=${GIT_BRANCH}
      - GIT_REPO_ORIGIN=${GIT_REPO_ORIGIN}
      - GIT_REPO_NAME=${GIT_REPO_NAME}
      - GIT_REPO_PATH=${GIT_REPO_PATH}
      - DOCKERFILE=${DOCKERFILE}
      - DOCKERFILE_PATH=${DOCKERFILE_PATH}
      - BITCOIN_CONF=${BITCOIN_CONF}
      - BITCOIN_DATA_DIR=${BITCOIN_DATA_DIR}
      - STATOSHI_DATA_DIR=${STATOSHI_DATA_DIR}
      - NO_CACHE=${NO_CACHE}
      - VERBOSE=${VERBOSE}
      - PUBLIC_PORT=${PUBLIC_PORT}
      - PASSWORD=${PASSWORD}
      - CMD_ARGUMENTS=${CMD_ARGUMENTS}
    # Run with user priviliges by default.
    user: ${HOST_USER:-nodummy}
    image: ${PROJECT_NAME}:${HOST_USER:-nodummy}
    restart: unless-stopped
    build:
      context: .
      # This is the name of the last layer in shell
      dockerfile: shell
      # These variables are passed to Dockerfile.
      args:
        - PWD=${PWD}
        - UMBREL=${UMBREL}
        - THIS_FILE=${THIS_FILE}
        - TIME=${TIME}
        - HOST_USER=${HOST_USER}
        - HOST_UID=${HOST_UID}
        - SERVICE_TARGET=${SERVICE_TARGET}
        - ALPINE_VERSION=${ALPINE_VERSION}
        - WHISPER_VERSION=${WHISPER_VERSION}
        - CARBON_VERSION=${CARBON_VERSION}
        - GRAPHITE_VERSION=${GRAPHITE_VERSION}
        - STATSD_VERSION=${STATSD_VERSION}
        - GRAFANA_VERSION=${GRAFANA_VERSION}
        - PROJECT_NAME=${PROJECT_NAME}
        - GIT_USER_NAME=${GIT_USER_NAME}
        - GIT_USER_EMAIL=${GIT_USER_EMAIL}
        - GIT_SERVER=${GIT_SERVER}
        - GIT_PROFILE=${GIT_PROFILE}
        - GIT_BRANCH=${GIT_BRANCH}
        - GIT_REPO_ORIGIN=${GIT_REPO_ORIGIN}
        - GIT_REPO_NAME=${GIT_REPO_NAME}
        - GIT_REPO_PATH=${GIT_REPO_PATH}
        - DOCKERFILE=${DOCKERFILE}
        - DOCKERFILE_PATH=${DOCKERFILE_PATH}
        - BITCOIN_CONF=${BITCOIN_CONF}
        - BITCOIN_DATA_DIR=${BITCOIN_DATA_DIR}
        - STATOSHI_DATA_DIR=${STATOSHI_DATA_DIR}
        - NO_CACHE=${NO_CACHE}
        - VERBOSE=${VERBOSE}
        - PUBLIC_PORT=${PUBLIC_PORT}
        - PASSWORD=${PASSWORD}
        - CMD_ARGUMENTS=${CMD_ARGUMENTS}
    # Run container as a service. Replace with something useful.
    #command: ["tail", "-f", "/dev/null"]
    # Copy current (git-) project into container.
    volumes:
      - ${HOME:-.}:/home/${HOST_USER}:consistent
      - ${BITCOIN_DATA_DIR:-.}:/home/${HOST_USER}/${BITCOIN_DATA_DIR}:consistent
      - ${STATOSHI_DATA_DIR:-.}:/home/${HOST_USER}/${STATOSHI_DATA_DIR}:consistent

  header:
    # Makefile fills PROJECT_NAME to current directory name.
    # add UID to allow multiple users run this in parallel
    container_name: ${PROJECT_NAME}_${HOST_UID:-4000}
    hostname: ${PROJECT_NAME}
    # These variables are passed into the container.
    environment:
      - PWD=${PWD}
      - UMBREL=${UMBREL}
      - THIS_FILE=${THIS_FILE}
      - TIME=${TIME}
      - HOST_USER=${HOST_USER}
      - HOST_UID=${HOST_UID}
      - SERVICE_TARGET=${SERVICE_TARGET}
      - ALPINE_VERSION=${ALPINE_VERSION}
      - WHISPER_VERSION=${WHISPER_VERSION}
      - CARBON_VERSION=${CARBON_VERSION}
      - GRAPHITE_VERSION=${GRAPHITE_VERSION}
      - STATSD_VERSION=${STATSD_VERSION}
      - GRAFANA_VERSION=${GRAFANA_VERSION}
      - PROJECT_NAME=${PROJECT_NAME}
      - GIT_USER_NAME=${GIT_USER_NAME}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL}
      - GIT_SERVER=${GIT_SERVER}
      - GIT_PROFILE=${GIT_PROFILE}
      - GIT_BRANCH=${GIT_BRANCH}
      - GIT_REPO_ORIGIN=${GIT_REPO_ORIGIN}
      - GIT_REPO_NAME=${GIT_REPO_NAME}
      - GIT_REPO_PATH=${GIT_REPO_PATH}
      - DOCKERFILE=${DOCKERFILE}
      - DOCKERFILE_PATH=${DOCKERFILE_PATH}
      - BITCOIN_CONF=${BITCOIN_CONF}
      - BITCOIN_DATA_DIR=${BITCOIN_DATA_DIR}
      - STATOSHI_DATA_DIR=${STATOSHI_DATA_DIR}
      - NO_CACHE=${NO_CACHE}
      - VERBOSE=${VERBOSE}
      - PUBLIC_PORT=${PUBLIC_PORT}
      - PASSWORD=${PASSWORD}
      - CMD_ARGUMENTS=${CMD_ARGUMENTS}
    # Run with user priviliges by default.
    user: ${HOST_USER:-nodummy}
    image: ${PROJECT_NAME}:${HOST_USER:-nodummy}
    restart: unless-stopped
    build:
      context: .
      # This is the name of the last layer in shell
      dockerfile: docker/header
      # These variables are passed to Dockerfile.
      args:
        - PWD=${PWD}
        - UMBREL=${UMBREL}
        - THIS_FILE=${THIS_FILE}
        - TIME=${TIME}
        - HOST_USER=${HOST_USER}
        - HOST_UID=${HOST_UID}
        - SERVICE_TARGET=${SERVICE_TARGET}
        - ALPINE_VERSION=${ALPINE_VERSION}
        - WHISPER_VERSION=${WHISPER_VERSION}
        - CARBON_VERSION=${CARBON_VERSION}
        - GRAPHITE_VERSION=${GRAPHITE_VERSION}
        - STATSD_VERSION=${STATSD_VERSION}
        - GRAFANA_VERSION=${GRAFANA_VERSION}
        - PROJECT_NAME=${PROJECT_NAME}
        - GIT_USER_NAME=${GIT_USER_NAME}
        - GIT_USER_EMAIL=${GIT_USER_EMAIL}
        - GIT_SERVER=${GIT_SERVER}
        - GIT_PROFILE=${GIT_PROFILE}
        - GIT_BRANCH=${GIT_BRANCH}
        - GIT_REPO_ORIGIN=${GIT_REPO_ORIGIN}
        - GIT_REPO_NAME=${GIT_REPO_NAME}
        - GIT_REPO_PATH=${GIT_REPO_PATH}
        - DOCKERFILE=${DOCKERFILE}
        - DOCKERFILE_PATH=${DOCKERFILE_PATH}
        - BITCOIN_CONF=${BITCOIN_CONF}
        - BITCOIN_DATA_DIR=${BITCOIN_DATA_DIR}
        - STATOSHI_DATA_DIR=${STATOSHI_DATA_DIR}
        - NO_CACHE=${NO_CACHE}
        - VERBOSE=${VERBOSE}
        - PUBLIC_PORT=${PUBLIC_PORT}
        - PASSWORD=${PASSWORD}
        - CMD_ARGUMENTS=${CMD_ARGUMENTS}
    # Run container as a service. Replace with something useful.
    #command: ["tail", "-f", "/dev/null"]
    # Copy current (git-) project into container.
    volumes:
      - ${HOME:-.}:/home/${HOST_USER}:consistent
      - ${BITCOIN_DATA_DIR:-.}:/home/${HOST_USER}/${BITCOIN_DATA_DIR}:consistent
      - ${STATOSHI_DATA_DIR:-.}:/home/${HOST_USER}/${STATOSHI_DATA_DIR}:consistent

  statoshi:
    # Makefile fills PROJECT_NAME to current directory name.
    # add UID to allow multiple users run this in parallel
    container_name: ${PROJECT_NAME}_${HOST_UID:-4000}
    hostname: ${PROJECT_NAME}
    # These variables are passed into the container.
    environment:
      - PWD=${PWD}
      - UMBREL=${UMBREL}
      - THIS_FILE=${THIS_FILE}
      - TIME=${TIME}
      - HOST_USER=${HOST_USER}
      - HOST_UID=${HOST_UID}
      - SERVICE_TARGET=${SERVICE_TARGET}
      - ALPINE_VERSION=${ALPINE_VERSION}
      - WHISPER_VERSION=${WHISPER_VERSION}
      - CARBON_VERSION=${CARBON_VERSION}
      - GRAPHITE_VERSION=${GRAPHITE_VERSION}
      - STATSD_VERSION=${STATSD_VERSION}
      - GRAFANA_VERSION=${GRAFANA_VERSION}
      - PROJECT_NAME=${PROJECT_NAME}
      - GIT_USER_NAME=${GIT_USER_NAME}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL}
      - GIT_SERVER=${GIT_SERVER}
      - GIT_PROFILE=${GIT_PROFILE}
      - GIT_BRANCH=${GIT_BRANCH}
      - GIT_REPO_ORIGIN=${GIT_REPO_ORIGIN}
      - GIT_REPO_NAME=${GIT_REPO_NAME}
      - GIT_REPO_PATH=${GIT_REPO_PATH}
      - DOCKERFILE=${DOCKERFILE}
      - DOCKERFILE_PATH=${DOCKERFILE_PATH}
      - BITCOIN_CONF=${BITCOIN_CONF}
      - BITCOIN_DATA_DIR=${BITCOIN_DATA_DIR}
      - STATOSHI_DATA_DIR=${STATOSHI_DATA_DIR}
      - NO_CACHE=${NO_CACHE}
      - VERBOSE=${VERBOSE}
      - PUBLIC_PORT=${PUBLIC_PORT}
      - PASSWORD=${PASSWORD}
      - CMD_ARGUMENTS=${CMD_ARGUMENTS}
    # Run with user priviliges by default.
    user: ${HOST_USER:-nodummy}
    image: ${PROJECT_NAME}:${HOST_USER:-nodummy}
    restart: unless-stopped
    build:
      context: .
      # This is the name of the last layer in stats.bitcoincore.dev
      dockerfile: ${PROJECT_NAME}
      # These variables are passed to Dockerfile.
      args:
        - PWD=${PWD}
        - UMBREL=${UMBREL}
        - THIS_FILE=${THIS_FILE}
        - TIME=${TIME}
        - HOST_USER=${HOST_USER}
        - HOST_UID=${HOST_UID}
        - SERVICE_TARGET=${SERVICE_TARGET}
        - ALPINE_VERSION=${ALPINE_VERSION}
        - WHISPER_VERSION=${WHISPER_VERSION}
        - CARBON_VERSION=${CARBON_VERSION}
        - GRAPHITE_VERSION=${GRAPHITE_VERSION}
        - STATSD_VERSION=${STATSD_VERSION}
        - GRAFANA_VERSION=${GRAFANA_VERSION}
        - PROJECT_NAME=${PROJECT_NAME}
        - GIT_USER_NAME=${GIT_USER_NAME}
        - GIT_USER_EMAIL=${GIT_USER_EMAIL}
        - GIT_SERVER=${GIT_SERVER}
        - GIT_PROFILE=${GIT_PROFILE}
        - GIT_BRANCH=${GIT_BRANCH}
        - GIT_REPO_ORIGIN=${GIT_REPO_ORIGIN}
        - GIT_REPO_NAME=${GIT_REPO_NAME}
        - GIT_REPO_PATH=${GIT_REPO_PATH}
        - DOCKERFILE=${DOCKERFILE}
        - DOCKERFILE_PATH=${DOCKERFILE_PATH}
        - BITCOIN_CONF=${BITCOIN_CONF}
        - BITCOIN_DATA_DIR=${BITCOIN_DATA_DIR}
        - STATOSHI_DATA_DIR=${STATOSHI_DATA_DIR}
        - NO_CACHE=${NO_CACHE}
        - VERBOSE=${VERBOSE}
        - PUBLIC_PORT=${PUBLIC_PORT}
        - PASSWORD=${PASSWORD}
        - CMD_ARGUMENTS=${CMD_ARGUMENTS}
    # Run container as a service. Replace with something useful.
    #command: ["tail", "-f", "/dev/null"]
    command:  ["/entrypoint"]
    # Expose current project folder to container.
    volumes:
      - ${HOME:-.}:/home/${HOST_USER}:consistent
      - ${BITCOIN_DATA_DIR:-.}:/home/${HOST_USER}/${BITCOIN_DATA_DIR}:consistent
      - ${STATOSHI_DATA_DIR:-.}:/home/${HOST_USER}/${STATOSHI_DATA_DIR}:consistent
    ports:
       #hostPORT:imagePORT
     - "8332:8332"
     - "8333:8333"
     - "18333:18333"

  torproxy:
    # Makefile fills PROJECT_NAME to current directory name.
    # add UID to allow multiple users run this in parallel
    container_name: ${PROJECT_NAME}_${HOST_UID:-4000}
    hostname: ${PROJECT_NAME}
    # These variables are passed into the container.
    environment:
      - PWD=${PWD}
      - UMBREL=${UMBREL}
      - TIME=${TIME}
      - HOST_USER=${HOST_USER}
      - HOST_UID=${HOST_UID}
      - SERVICE_TARGET=${SERVICE_TARGET}
      - ALPINE_VERSION=${ALPINE_VERSION}
      - PROJECT_NAME=${PROJECT_NAME}
      - GIT_USER_NAME=${GIT_USER_NAME}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL}
      - GIT_SERVER=${GIT_SERVER}
      - GIT_PROFILE=${GIT_PROFILE}
      - GIT_BRANCH=${GIT_BRANCH}
      - GIT_REPO_ORIGIN=${GIT_REPO_ORIGIN}
      - GIT_REPO_NAME=${GIT_REPO_NAME}
      - GIT_REPO_PATH=${GIT_REPO_PATH}
      - NO_CACHE=${NO_CACHE}
      - VERBOSE=${VERBOSE}
      - PUBLIC_PORT=${PUBLIC_PORT}
      - PASSWORD=${PASSWORD}
      - CMD_ARGUMENTS=${CMD_ARGUMENTS}
    # Run with user priviliges by default.
    user: ${HOST_USER:-nodummy}
    image: ${PROJECT_NAME}_torproxy:${HOST_USER:-nodummy}
    restart: unless-stopped
    build:
      context: .
      # This is the name of the last layer in stats.bitcoincore.dev.slim
      dockerfile: torproxy
      # These variables are passed to Dockerfile.
      args:
        - PWD=${PWD}
        - UMBREL=${UMBREL}
        - TIME=${TIME}
        - HOST_USER=${HOST_USER}
        - HOST_UID=${HOST_UID}
        - SERVICE_TARGET=${SERVICE_TARGET}
        - ALPINE_VERSION=${ALPINE_VERSION}
        - PROJECT_NAME=${PROJECT_NAME}
        - GIT_USER_NAME=${GIT_USER_NAME}
        - GIT_USER_EMAIL=${GIT_USER_EMAIL}
        - GIT_SERVER=${GIT_SERVER}
        - GIT_PROFILE=${GIT_PROFILE}
        - GIT_REPO_ORIGIN=${GIT_REPO_ORIGIN}
        - GIT_REPO_NAME=${GIT_REPO_NAME}
        - GIT_REPO_PATH=${GIT_REPO_PATH}
        - NO_CACHE=${NO_CACHE}
        - VERBOSE=${VERBOSE}
        - PUBLIC_PORT=${PUBLIC_PORT}
        - PASSWORD=${PASSWORD}
        - CMD_ARGUMENTS=${CMD_ARGUMENTS}
    # Run container as a service. Replace with something useful.
    #command: ["tail", "-f", "/dev/null"]
    command:  ["/sbin/tini", "--", "/usr/bin/torproxy.sh"]
    # Expose current project folder to container.
    volumes:
      - /etc/tor
      - /var/lib/tor
    ports:
       #hostPORT:imagePORT
       #we expose tor proxy ports for 'make torproxy'
     - "8118:8118"
     - "9050:9050"
     - "9051:9051"

